---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: example-app
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: example-app
  labels:
    prometheus: example-app
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      prometheus: example-app
  endpoints:
  - port: web