apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring
  labels:
    svc: pushgateway
spec:
  type: NodePort
  ports:
  - name: push-port
    port: 9091
    targetPort: push-port
    protocol: TCP
  selector:
    k8s: pushgateway
