apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-rules
  namespace: monitoring
  labels:
    rule: alerts
spec:
  groups:
  - name: node-exporter
    interval: 30s
    rules:
    - alert: NodeIsDown
      expr: up{service="node-exporter"} == 0
      for: 30s
      labels:
        severity: critical
      annotations:
        description: Node-exporter agent on {{ .Labels.instance }} is down
        summary: Node-exporter is down
