---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-one
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app-one
  template:
    metadata:
      labels:
        app: example-app-one
    spec:
      containers:
      - name: example-app-one
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: example-app-one
  namespace: monitoring
  labels:
    app: example-app
spec:
  selector:
    app: example-app-one
  ports:
  - name: web
    port: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  namespace: monitoring
  labels:
    name: example-app-svcmon
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
